### ISSUE TITLE
[BE] API 스펙 수정

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#124]
### 🔨 Describe

API 스펙 수정하려구요!

### ✅ Tasks

- [x] 조회 API Fix
- [x] 필터마다 여러개의 항목을 선택할 수 있다.
- [x] 키워드와 주원료는 다르다

### 🕖 예상 작업 소요 시간

1시간
