### ISSUE TITLE
식품 목록 조회 API 인터페이스 구현

### ISSUE THREAD

**Issue by ksone02** [woowacourse-teams/2023-zipgo#13]
### ✨ Describe

식품 목록 조회 API 추상화 및 
Suspense와 ErrorBoundary 활용해 인터페이스 구축

### ✅ Tasks

- [x] API 공용 인터페이스 구현
- [x] 식품 조회 API 구현
- [x] Suspense, ErrorBoundary 추상화

### 🙋🏻 More

ErrorBoundary -> 라이브러리 사용 가능 여부 확인필요
