### ISSUE TITLE
[BE] Filtering 관련 정보 제공

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#151]
### 🔨 Describe

현재 Filtering 관련 정보들을 하드코딩해서 반환해주고 있는데요, 국가 영양만족 기준에 id가 없어서 당장 동적으로 조회하는 기능을 만들 순 없지만, 추후에 해당 값만 추가하면 기능이 완성되게끔 만들어 놓겠습니다

### ✅ Tasks
- [x] #165
- [x] 필터링 조회 영양기준 정보 추가
- [x] 필터링 정보 메타데이터 조회
  - [x] 추후에 영양기준 id 추가

### 🕖 예상 작업 소요 시간
2시간
