### ISSUE TITLE
[FE] 에러 핸들링 고도화

### ISSUE THREAD

**Issue by n0eyes** [woowacourse-teams/2023-zipgo#205]
### ✨ Describe

런타임에러와 api 에러를 종류에 따라 구분하여 핸들링할 수 있도록 `ErrorBoundary`를 고도화한다

### ✅ Tasks

- [x] 런타임 에러 핸들링
- [x] api 에러 핸들링
  - [x] Unexpected Error
  - [x] 네트워크 에러
  - [x] 응답 없음 에러
  - [x] 응답 있음 에러

### 🕖 예상 작업 소요 시간

24시간
