### ISSUE TITLE
프로덕션 환경 구축

### ISSUE THREAD

**Issue by iamjooon2** [woowacourse-teams/2023-zipgo#206]
### 🧚🏻‍♀️ Describe

프로덕션 환경을 구축하고 배포합니다

### ✅ Tasks

- [ ] 프로덕션 서버 빌드&배포 환경 구축
- [ ] 프로덕션 서버 배포
    - [ ] 백엔드 서버 배포
