### ISSUE TITLE
[BE] 리뷰 조회 API 리뷰 정렬 및 필터 기능 추가

### ISSUE THREAD

**Issue by kyY00n** [woowacourse-teams/2023-zipgo#207]
### ✨ Describe

리뷰 정렬, 필터 기능을 구현합니다.
필터 기능과 분리가 어려운 기능이라 같이 작업하게 될 것 같습니다.

페이징은 별도로 작업이 가능할 것 같아, PR 범위도 줄일 겸 별도로 작업하겠습니다.

### ✅ Tasks

- [ ] 리뷰 도메인 수정 염탐하기
  - [ ] 반려동물 정보 도메인도 함께.

### 정렬 기준

- [ ] 최신순
- [ ] 도움이 되는 순
- [ ] 별점 높은 순
- [ ] 별점 낮은 순

### 필터 기능

- [ ] 소/중/대형견 선택
  - [ ] 아무것도 선택하지 않음 / 여러 개를 선택한 경우 어떻게 처리할지 논의
- [ ] 견종 필터
  - [ ] 믹스견 선택할 경우 어떻게 처리할지 논의
- [ ] 퍼피/어덜트/시니어 (나이대) 선택
  - [ ] 전연령대상 식품은 모든 검색에 나와야하는지 논의

### 🕖 예상 작업 소요 시간

진짜 가늠이 안가는데.. 얼마나 걸릴지
일단 내일 밥먹고 1시부터 6시 내로 할 수 있을까요?

&rarr; 5h

### 🙋🏻 More

빨리 시도하고 빨리 리뷰를 받아야할 것 같아서.. 마음이 급해지네용
