### ISSUE TITLE
서버 배포 스크립트 작성

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#23]
### ✨ Describe

서버를 배포할 때 필요한 스크립트를 작성하려고 합니다. 서버가 비정상적으로 종료되었을 때 스크립트가 유실되면 안되기 때문에 깃으로 같이 관리하기로 했습니다.

### ✅ Tasks

- [x] 현재 구동중인 애플리케이션 PID 확인
  - [x] 만약 현재 구동중인 애플리케이션이 있다면 해당 포트 킬
- [x] 없다면 바로 배포
  - [x] profiles 설정
  - [x] 환경변수 properties 파일 설정
  - [x] 백그라운드로 실행
