### ISSUE TITLE
[BE] PetFood 엔티티 연관관계 리팩터링

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#234]
### 🔨 Describe

클라이언트에 값을 반환해줄 때 이름이 같은 기능성과 주원료는 중복을 제거한 다음 해당 pet_food_id와 함께 반환하는데, 그렇게 되면 중복제거된 pet_food_id는 반환되지 못하는 문제가 발생하여 ManyToMany 관계로 변경해야 합니다.

### ✅ Tasks

- [x] PrimaryIngredientRepository.findDistinctPrimaryIngredients() 수정
- [x] FunctionalityRepository.findDistinctFunctionalities() 수정
- [x] PetFood <-> PrimaryIngredient ManyToMany로 변경
- [x] PetFood <-> Functionality ManyToMany로 변경

### 🕖 예상 작업 소요 시간

3시간
