### ISSUE TITLE
[BE] 리뷰 도메인에 도움이 돼요, 리뷰 당시 반려동물 정보 추가

### ISSUE THREAD

**Issue by kyY00n** [woowacourse-teams/2023-zipgo#238]
### ✨ Describe

# As is

<img width="302" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/c82552d7-4730-459c-b7d5-d5ba05294135">

# To be

<img width="429" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/1add0c6b-5994-4b08-b0eb-007d6d4a31ff">

### ✅ Tasks

수정해야하는 항목
- [x] 리뷰에는 유저가 아니라 강아지가 연결돼야함.

추가되어야하는 항목
- [x] 도움이 돼요(좋아요)
- [x] 리뷰 당시 나이
- [x] 리뷰 당시 몸무게

### 🕖 예상 작업 소요 시간

0.5h
제발!
