### ISSUE TITLE
[FE] 식품 상세페이지 도움말 토글 추가

### ISSUE THREAD

**Issue by ksone02** [woowacourse-teams/2023-zipgo#256]
### ✨ Describe

식품 상세페이지의 엘리먼트들에 도움말 토글을 추가합니다.

### ✅ Tasks

- [x] 토글 컴포넌트 만들기
- [x] 브랜드 상세 정보 토글
  - [x] 브랜드 상세 정보 필요한 이유 토글
  - [x] 연구센터 여부 토글
  - [x] 국가별 토글
  - [x] 수의사 여부 토글
  - [x] 브랜드 창립연도 토글
- [x] 기준 충족 여부 토글

### 🕖 예상 작업 소요 시간

3시간
