### ISSUE TITLE
[FE] 펫 정보 수정 시 context update, 로컬 스토리지 데이터에 따른 리뷰 작성 버튼 렌더링 여부 설정

### ISSUE THREAD

**Issue by HyeryongChoi** [woowacourse-teams/2023-zipgo#304]
### ✨ Describe

#303 
> 펫 프로필이랑 로그아웃 구현했습니다
>
>  근데 펫 프로필을 context로 쓰고 있는데.. 흠
>
>  추가적으로 필요한 게 있어요.
>
> 펫 정보 수정했을 때 context update
> 리뷰 작성 버튼 존재 여부를 context? 또는 storage에 따라 다르게 줘야 합니다..

### ✅ Tasks

- [x] 펫 정보 추가, 수정, 삭제 시 context update
- [x] 로컬 스토리지 데이터에 따른 리뷰 작성 버튼 렌더링 여부 설정
- [x] 펫 정보 추가 시 로컬 스토리지 userInfo의 hasPet을 true로 변경
- [x] 펫 정보 삭제 시 로컬 스토리지 userInfo의 hasPet을 false로 변경
- [x] 몸무게 inputMode numeric > decimal로 변경
- [ ] 펫 정보 수정 페이지에서 최신 변경사항이 반영되지 않는 문제 해결
  - 펫 정보 수정 완료 시 캐시된 이전 데이터 reset
- [x] develop 서버에서 사용하는 API 주소 변경
- [x] 모바일에서 Input 요소 클릭 시 화면 확대되지 않도록 설정

### 🕖 예상 작업 소요 시간

2시간..?
