### ISSUE TITLE
[FE] 로그인 시 사용자 id, 리뷰 조회 시 작성자 id 등 api 명세 수정

### ISSUE THREAD

**Issue by HyeryongChoi** [woowacourse-teams/2023-zipgo#357]
### 로그인 응답
로그인 시 사용자 id, email 및 반려동물 정보를 함께 반환 받도록 수정하고자 합니다.

두 정보는 아래와 같은 상황에서 사용됩니다.
1. 반려동물 정보 ➡️ 로그인 시 반려동물 프로필을 보여주기 위한 정보
2. 사용자 id, email ➡️ 리뷰 수정, 삭제, 도움이 돼요 등 사용자를 구분하기 위한 정보

```JSON
// 반려동물 존재할 때
{
  "accessToken" : "생성된_토큰",
  "authResponse" : {
   "id": 123,
    "name" : "이름",
    "email" : "이메일",
    "profileImageUrl" : "사진",
    "hasPet" : true,
    "pets" : [
      {
        "id": 1,
        "imageUrl" : "https://image.zipgo.pet/dev/pet-image/dog_icon.svg",
        "name" : "무민이",
        ...
      },
      ...
    ]
  }
}

// 반려동물 없을때
{
  "accessToken" : "생성된_토큰",
  "authResponse" : {
   "id": 123,
    "name" : "이름",
    "email" : "이메일",
    "profileImageUrl" : "사진",
    "hasPet" : false,
    "pets" : []
  }
}
```

### 리뷰 조회 응답
작성자 id로 본인의 리뷰인지 확인할 수 있도록 writerId를 리뷰 조회 응답에 추가하고자합니다. (리뷰 개별 조회, 리뷰 목록 조회)

```JSON
{
  "id": 1,
  "writerId": 1,
  "rating": 5,
  "date": "2023-09-11",
  "comment": "우리 아이랑 너무 잘 맞아요!",
  "tastePreference": "정말 잘 먹어요",
  "stoolCondition": "촉촉 말랑해요",
  "adverseReactions": [
    "없어요"
  ],
  "petProfile": {
    "id": 1,
    "name": "무민이",
    "profileUrl": "https://image.zipgo.pet/dev/pet-image/dog_icon.svg",
    "writtenAge": 4,
    "writtenWeight": 0,
    "breed": {
      "id": 1,
      "name": "푸들",
      "size": {
        "id": 1,
        "name": "소형견"
      }
    }
  },
  "helpfulReaction": {
    "count": 0,
    "reacted": false
  }
}
```

## ✅ Tasks

- [x] `로그아웃 하고 다시 로그인 했을 때 반려견 정보를 선택하는 점이 불편해요.` 피드백 반영
- [x] 로그인 응답 수정
- [x] 리뷰 조회 응답 수정 
- [x] 중복된 petProfile 타입 삭제
- [x] 로그인 시 반려동물 프로필 정보 로컬스토리지에 저장
- [x] 로컬에서만 MSW 실행되도록 설정 

### 🕖 예상 작업 소요 시간

1시간
