### ISSUE TITLE
[FE] 로그인 여부 확인 로직 수정

### ISSUE THREAD

**Issue by n0eyes** [woowacourse-teams/2023-zipgo#363]
### 🔨 Describe

기존에 `/auth` api를 통해 확인하던 로그인 여부를 토큰의 여부로 확인하는 방식으로 변경

### ✅ Tasks

- [ ] `/auth` api를 통해 확인하던 로그인 여부를 토큰의 여부로 확인하는 방식으로 변경
- [ ] `/auth` api 호출 전 로그인 여부 확인 로직 추가
- [ ] `AxiosIntercepotr`에 토큰 유무 확인 로직 추가

### 🕖 예상 작업 소요 시간

5시간
