### ISSUE TITLE
[BE] 사용자에게 직접적으로 노출되는 화면을 위한 레이어 분리해보기

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-zipgo#368]
### 🔨 Describe

보통 CQS를 도입하고, 커맨드와 쿼리를 완전하게 분리하기 위해서 사용자에게 노출되는 화면을 위한 데이터를 조합하는 레이어를 별도로 만든다고 합니다! 이 부분도 따로 이슈/브랜치를 파서 작업해보겠습니다

### ✅ Tasks

- [ ] query라는 별도의 패키지로 분리
  - [ ] query 패키지 안에서 도메인 분리
  - [ ] 복잡한 쿼리는 해당 패키지/도메인의 외부 모듈 + 도메인명 + Reader로 처리
    - [ ] Ex: QuerydslReviewReader
- [ ] ReviewQueryService는 필요한 도메인의 QueryService를 조합하여 ReviewQueryController에게 값을 반환한다.

### 🕖 예상 작업 소요 시간

3시간
