### ISSUE TITLE
[FE] 반려동물 여러마리 등록 기능 추가

### ISSUE THREAD

**Issue by HyeryongChoi** [woowacourse-teams/2023-zipgo#396]
### ✨ Describe

반려동물 여러마리 등록 기능을 추가하려고 해여 + 기타 작은 작업들

### ✅ Tasks

- [x] 반려동물 등록 버튼 항상 보이도록 수정
- [x] 리뷰 등록 시 petId도 함께 전달하도록 수정
- [x] Dockerfile 스토리북 배포 설정
- [x] 로그인 시 사용자의 반려동물 프로필이 헤더에 즉시 적용되도록 설정
- [x] 반려동물 정보 삭제 시 헤더 프로필 업데이트

### 🕖 예상 작업 소요 시간

1시간..?
