### ISSUE TITLE
[FE] 메인페이지 하단 '사료 선택 도움말 배너' 추가

### ISSUE THREAD

**Issue by HyeryongChoi** [woowacourse-teams/2023-zipgo#457]
### ✨ Describe

우리 서비스에서 고민한 부분이 잘 전달 되도록 UI/UX를 개선하기 위해
[사료 선택 도움말 페이지 링크](https://translucent-mallet-426.notion.site/dae305b85c8146399d7de6a0e74b773d?pvs=4)로 이동시키는 사료 선택 도움말 배너를 추가하려고 합니다.

**👀 예시 이미지(펫프렌즈)**
<img height="500" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/24777828/d8bb7921-cf42-41af-b0db-1b751519e30a">

### ✅ Tasks

- [x] 사료 선택 도움말 배너
  - [x] 닫기 버튼을 통해 배너를 닫을 수 있어야 한다.
  - [x] 배너 클릭 시 사료 선택 도움말 페이지 링크로 이동해야 한다.

### 🕖 예상 작업 소요 시간

3시간?
