### ISSUE TITLE
[FE] 식품 이미지 lazy loading 적용

### ISSUE THREAD

**Issue by n0eyes** [woowacourse-teams/2023-zipgo#528]
### 🔨 Describe

미처 적용이 되지 않은 식품 이미지에 lazy loading을 적용한다.

### ✅ Tasks

- [ ] FoodItem lazy loading 적용
- [ ] `LazyImg`가 ref를 사용할 수 있도록 보강
- [ ] `SuspendedImg`의 lazy 기능을 `LazyImg`를 활용하여 병합

### 🕖 예상 작업 소요 시간

3시간
