### ISSUE TITLE
[BE] 식품 정보 상세 조회 API 구현

### ISSUE THREAD

**Issue by kyY00n** [woowacourse-teams/2023-zipgo#59]
### ✨ Describe

식품의 상세정보를 조회하는 API를 구현합니다.

### ✅ Tasks

- [ ]  식품명, 식품 이미지를 확인할 수 있다.
- [ ]  주단백질원을 확인할 수 있다.
- [ ]  기능성 정보를 확인할 수 있다.
- [ ]  구매링크로 이동할 수 있는 버튼이 있다.
- [ ]  미국, 유럽 영양소 기준 만족 여부를 확인할 수 있다.
- [ ]  브랜드 정보를 확인할 수 있다.
    - [ ]  브랜드명을 확인할 수 있다.
    - [ ]  브랜드의 국가를 확인할 수 있다.
    - [ ]  브랜드의 창립연도를 확인할 수 있다.
    - [ ]  브랜드 전용 연구센터가 존재하는지 확인할 수 있다.
    - [ ]  브랜드에 상주하는 수의사가 있는지 확인할 수 있다.

### 🕖 예상 작업 소요 시간

저는 목욜까지 해보겠습니다. 금욜에 리뷰 받을 수 있으면 좋을 거같아요

단백질원, 기능성, 주 단백질원, 영양소 기준 만족 여부 추가하기 - 0.5h
브랜드 도메인 만들기 - 이름, 국가, 창립연도, 연구센터 유무, 수의사 유무 - 0.5h
조회하기 서비스/테스트 - 1h
API 구현 및 테스트 - 1h
데이터베이스 구현 및 연결 -1h

트러블 슈팅..? 가능성까지 잡아보았는데, 총 4h 나왔습니다.
중간에 쉬면서 하면 반나절은 걸릴 것 같습니다.
근데 하루에 다 하지도 않을 거같은데여..? ㅋㅋㄹㅋ쿠ㅜㅜ
