### ISSUE TITLE
[FE] 식품 정보 상세 페이지 구현

### ISSUE THREAD

**Issue by ksone02** [woowacourse-teams/2023-zipgo#62]
### ✨ Describe

식품 목록에서 식품 아이템을 선택했을 때 이동되는 식품의 상세 정보를 확인할 수 있는 페이지를 맡아서 개발, 구현합니다.

### ✅ Tasks

- [x]  식품명, 식품 이미지를 확인할 수 있다.
- [x]  주단백질원을 확인할 수 있다.
- [x]  기능성 정보를 확인할 수 있다.
- [x]  구매링크로 이동할 수 있는 버튼이 있다.
- [x]  미국, 유럽 영양소 기준 만족 여부를 확인할 수 있다.
- [x]  브랜드 정보를 확인할 수 있다.
    - [x]  브랜드명을 확인할 수 있다.
    - [x]  브랜드의 국가를 확인할 수 있다.
    - [x]  브랜드의 창립연도를 확인할 수 있다.
    - [x]  브랜드 전용 연구센터가 존재하는지 확인할 수 있다.
    - [x]  브랜드에 상주하는 수의사가 있는지 확인할 수 있다.

### 🕖 예상 작업 소요 시간

~8/1(화)
