### ISSUE TITLE
프론트엔드 ```CI/CD``` 구축

### ISSUE THREAD

**Issue by ksone02** [woowacourse-teams/2023-zipgo#8]
### ✨ Describe

AWS EC2, Github Actions 활용해 CI/CD 환경 구축
CI 과정에서 테스트는 추후 구현 예정

### ✅ Tasks

- [x] AWS EC2 docker 설정
- [x] Dockerfile 생성, nginx 설정
- [x] Jenkins pipeline 구축
