### ISSUE TITLE
[BE] 식품 상세 조회를 조회서비스로 분리

### ISSUE THREAD

**Issue by kyY00n** [woowacourse-teams/2023-zipgo#85]
### 🔨 Describe

현재의 식품 상세 뷰를 위한 데이터 조회 기능을 조회서비스로 분리한다.

> 아까 잠깐 얘기한거 적고 가자면,
> 1. 우선 기능 개발이 우선이라 생각해서, 이렇게 구현하고 넘어가는 것도 좋다고 생각하고, 현재 딱히 문제되는 부분은 없다고 생각해!
> 2. 그러나 이런 식으로 계속 코드를 작성한다면, Service에서 반환된 객체를 컨트롤러에서 사용하는 경우 [OSIV](https://ttl-blog.tistory.com/183)로 인해 문제가 생길 수 있어. 
>   - 부가 설명을 하자면, 스프링 부트에서는 OSIV를 기본적으로 true로 설정하지만, 이후 커넥션 낭비등을 최소화하기 위해 OSIV 옵션을 끊다면 그때 Lazy Loading 문제가 발생할 수 있어. 이런 경우를 대비하고자, 조회를 위한 객체를 QueryService에서 바로 반환하는 것이 좋다고 생각해.  추가적으로 이렇게 함으로써, 비즈니스 로직(명령)에는 아무런 영향 없이, 조회 성능을 극대화할 수도 있고.
> 
> 간단한 예시는 다음과 같을 거 같아.
> ```java
> @Service
> @Transactional
> @RequiredArgumentConstructor
> public class PetFoodService {
> 
>     private final PetFoodRepository petFoodRepository;
>     
>     pubic Long create() {
>     } 
> 
>     pubic void update() {
>     } 
> 
>     pubic void delete() {
>     } 
> }
> ```
> 
> 
> ```java
> @Service
> @Transactional(readOnly=true)
> @RequiredArgumentConstructor
> public class PetFoodService {
> 
>     private final PetFoodQueryRepository petFoodQueryRepository;
>     
>     public GetPetFoodsResponse getPetFoods(String keyword) {
>            return petFoodQueryRepository.getPetFoods(keyword);
>     }
> 
>     public GetPetFoodResponse getPetFood(Long id) {
>            return petFoodQueryRepository.getPetFood(id);
>     }
> }
> 
> ```

_Originally posted by @shin-mallang in https://github.com/woowacourse-teams/2023-zipgo/pull/80#discussion_r1276228714_
            

### ✅ Tasks

- [ ] PetFoodService에서 PetFoodQueryService로 옮기기
  - [ ] QueryService에서는 DTO 조립해 반환한다. 
- [ ] PetFoodQueryRepository 생성하기
  - [ ] QueryDsl 또는 jdbcTemplate을 사용. JpaRepository와 구분하여 사용하기.

### 🕖 예상 작업 소요 시간

- 서비스 분리: 0.3h
- QueryRepository 테스트 및 구현: 1h

넉넉잡아 2시간 걸릴 것 같습니다 :D
