### ISSUE TITLE
[BE] API 문서 실행 가능하게 하기

### ISSUE THREAD

**Issue by kyY00n** [woowacourse-teams/2023-zipgo#99]
### 🔨 Describe

실행이 안돼용 localhost 만 되게 해놔서 ㅋㅋㅋ
<img width="618" alt="image" src="https://github.com/woowacourse-teams/2023-zipgo/assets/61582017/bcdbb127-b40c-4657-aa4d-c6888d822806">

### ✅ Tasks

- [ ] 문서를 볼순있는데 api 실행은 안되네유..
- [ ] setServer에 우리 아이피를 직접 추가해야하나봐요
- [ ] 그리고 타입도 추가해주겠습니다

### 🕖 예상 작업 소요 시간

0.2h
